import type { Position } from 'geojson';
import { haversineKm } from './haversineKm.tsx';
import placesFile from './places.txt?raw';

// Place names for coordinates, so a stop dropped on the map can be named
// without asking the user to type one.
//
// The list (places.txt, generated by scripts/generate-places.mjs from GeoNames)
// holds every populated place in Norway and every Swedish one near the border —
// about 21 000 towns, villages, hamlets and city districts, each qualified with
// its municipality. It is deliberately bundled data rather than a geocoder
// call: naming a stop must never depend on a network round trip.
//
// A stop is named after the closest of those places, which for a pin out in the
// countryside is typically a kilometre or so away — near enough to tell a
// driver where to meet, not a street address.
//
// Half a megabyte of text is too much to put in the initial bundle, so nothing
// imports this module statically: the trip form pulls it in through
// loadNearestPlaceName, which Vite splits into a chunk of its own.

interface PlaceIndex {
  names: string[];
  // Parallel arrays rather than objects: one linear scan runs over 21 000
  // entries per lookup, and this keeps that allocation-free.
  latitudes: Float64Array;
  longitudes: Float64Array;
}

let index: PlaceIndex | null = null;

// "<name>|<latitude>|<longitude>" per line, '#' comments and a trailing blank
// line. Parsed once, on the first lookup.
const parse = (): PlaceIndex => {
  const lines = placesFile.split('\n');
  const names: string[] = [];
  const latitudes = new Float64Array(lines.length);
  const longitudes = new Float64Array(lines.length);

  for (const line of lines) {
    if (line === '' || line.startsWith('#')) {
      continue;
    }
    const lastBar = line.lastIndexOf('|');
    const firstBar = line.lastIndexOf('|', lastBar - 1);
    if (firstBar < 0) {
      continue;
    }
    const latitude = Number(line.slice(firstBar + 1, lastBar));
    const longitude = Number(line.slice(lastBar + 1));
    if (!Number.isFinite(latitude) || !Number.isFinite(longitude)) {
      continue;
    }
    latitudes[names.length] = latitude;
    longitudes[names.length] = longitude;
    names.push(line.slice(0, firstBar));
  }

  return {
    names,
    latitudes: latitudes.subarray(0, names.length),
    longitudes: longitudes.subarray(0, names.length),
  };
};

const placeIndex = (): PlaceIndex => (index ??= parse());

/**
 * The name to give a stop placed at `position`: the nearest known place.
 *
 * Returns an empty string only if the list itself failed to parse — callers
 * keep the name they already have in that case rather than blanking a field.
 */
export const nearestPlaceName = (position: Position): string => {
  const [longitude, latitude] = position;
  const { names, latitudes, longitudes } = placeIndex();

  let nearest = -1;
  let nearestDistance = Infinity;
  for (let i = 0; i < names.length; i++) {
    const distance = haversineKm(latitude, longitude, latitudes[i], longitudes[i]);
    if (distance < nearestDistance) {
      nearestDistance = distance;
      nearest = i;
    }
  }

  return nearest < 0 ? '' : names[nearest];
};

// Every place in the list, for tests that check the data itself.
export const placeNames = (): readonly string[] => placeIndex().names;
