name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test:run
      - name: Build
        run: npm run build
      - name: Archive build
        uses: actions/upload-artifact@v7.0.1
        with:
          name: dist
          path: dist

  prepare_dev:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download build
        uses: actions/download-artifact@v8.0.1
        with:
          name: dist
          path: dist
      - name: Copy bootstrap config
        run: cp .github/environments/config-dev.json dist/config.json
      - name: Copy theme config
        run: cp .github/environments/theme-dev.json dist/theme-dev.json
      - name: Archive dev build
        uses: actions/upload-artifact@v7.0.1
        with:
          name: dist-dev
          path: dist

  deploy_dev:
    needs: [prepare_dev]
    permissions:
      contents: read
      pull-requests: write
      id-token: write
    uses: entur/gha-firebase/.github/workflows/firebase-hosting-deploy.yml@v1.2.7
    with:
      gcp_project_id: ent-tadmustum-dev
      environment: dev
      build_artifact_name: dist-dev
      build_artifact_path: dist

  prepare_tst:
    needs: [deploy_dev]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download build
        uses: actions/download-artifact@v8.0.1
        with:
          name: dist
          path: dist
      - name: Copy bootstrap config
        run: cp .github/environments/config-tst.json dist/config.json
      - name: Copy theme config
        run: cp .github/environments/theme-tst.json dist/theme-tst.json
      - name: Archive tst build
        uses: actions/upload-artifact@v7.0.1
        with:
          name: dist-tst
          path: dist

  deploy_tst:
    needs: [prepare_tst]
    permissions:
      contents: read
      pull-requests: write
      id-token: write
    uses: entur/gha-firebase/.github/workflows/firebase-hosting-deploy.yml@v1.2.7
    with:
      gcp_project_id: ent-tadmustum-tst
      environment: tst
      build_artifact_name: dist-tst
      build_artifact_path: dist

  prepare_prd:
    needs: [deploy_tst]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download build
        uses: actions/download-artifact@v8.0.1
        with:
          name: dist
          path: dist
      - name: Copy bootstrap config
        run: cp .github/environments/config-prd.json dist/config.json
      - name: Copy theme config
        run: cp .github/environments/theme-prd.json dist/theme-prd.json
      - name: Archive prd build
        uses: actions/upload-artifact@v7.0.1
        with:
          name: dist-prd
          path: dist

  deploy_prd:
    needs: [prepare_prd]
    permissions:
      contents: read
      pull-requests: write
      id-token: write
    uses: entur/gha-firebase/.github/workflows/firebase-hosting-deploy.yml@v1.2.7
    with:
      gcp_project_id: ent-tadmustum-prd
      environment: prd
      build_artifact_name: dist-prd
      build_artifact_path: dist
